# Generated by Django 2.2.9 on 2020-01-30 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Agenda'), ('3', 'mesure'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('estPublic', models.BooleanField(default=False, verbose_name='Public ou réservé aux membres permacat')),
                ('estModifiable', models.BooleanField(default=False, verbose_name="Modifiable par n'importe qui")),
                ('date_dernierMessage', models.DateTimeField(auto_now=True, verbose_name='Date du dernier message')),
                ('dernierMessage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('estArchive', models.BooleanField(default=False, verbose_name="Archiver l'article")),
                ('start_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date (optionnel, pour affichage dans l'agenda)")),
                ('end_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)")),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
    ]
